a = int(input())
# b = int(input())
# print(f'a+=b: a= {a+b} b= {b}')
# print(f'a-=b: a= {a-b} b= {b}')
# print(f'a*=b: a= {a*b} b= {b}')
# print(f'a/=b: a= {b/a} b= {b}')
# print(f'a**=b: a= {a**b} b= {b}')
# print(f'a//=b: a= {a//b} b= {b}')
# print(f'a%=b: a= {a%b} b= {b}')
# print(f'a=b: a= {b} b= {b}')
